apiVersion: v2
name: bpa
description: The BPA allows organizations to verify, hold, and issue verifiable credentials.
type: application

version: 0.10.3
appVersion: 0.10.0

home: "https://github.com/hyperledger-labs/business-partner-agent-chart"
sources: ["https://github.com/hyperledger-labs/business-partner-agent-chart"]
maintainers:
  - email: Frank.Bernhardt@bosch.com
    name: frank-bee
    url: https://github.com/frank-bee
  - email: jsherman@parcsystems.ca
    name: usingtechnology
    url: https://github.com/parc-jason
  - email: jason.syrotuck@nttdata.com
    name: Jsyro
    url: https://github.com/Jsyro
dependencies:
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
