{{- $acapyIngressHost := include "acapy.host" . -}}
{{- $bpaIngressHost := include "bpa.host" . -}}
{{- $acapyUrl := (printf "http://%s:%g" (include "acapy.fullname" .) (.Values.acapy.service.adminPort)) -}}
{{- $acapyEndpoint := (printf "https://%s" ($acapyIngressHost)) -}}
{{- $didPrefix := include "acapy.didPrefix" . -}} 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bpa.fullname" . }}
  labels:
    {{- include "bpa.labels" . | nindent 4 }}
data:
  AGENT_NAME: {{ tpl .Values.bpa.config.name . | quote }}
  ACAPY_URL: {{ $acapyUrl | quote }}
  ACAPY_ENDPOINT: {{ $acapyEndpoint | quote }}
  ACAPY_API_KEY: {{ .Values.acapy.adminURLApiKey | quote }}
  POSTGRESQL_HOST: {{ include "global.postgresql.fullname" . | quote }}
  POSTGRESQL_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  BPA_SECURITY_ENABLED: {{ .Values.bpa.config.security.enabled | quote }}
  BPA_RESOLVER_URL: {{ tpl .Values.bpa.config.resolver.url . | quote }}
  BPA_LEDGER_BROWSER: {{ include "bpa.ledgerBrowser" . | quote }}
  BPA_HOST: {{ $bpaIngressHost | quote }}
  BPA_SCHEME: {{ .Values.bpa.config.scheme | quote }}
  BPA_WEB_MODE: {{ .Values.bpa.config.web.only | quote }}
  BPA_DID_PREFIX: {{ .Values.bpa.config.did.prefixOverride | default $didPrefix | quote }}
  BPA_BOOTSTRAP_UN: {{ .Values.bpa.config.bootstrap.username | quote }}
  BPA_BOOTSTRAP_PW: {{ .Values.bpa.config.bootstrap.password | quote }}
  BPA_CREDDEF_REVOCATION_REGISTRY_SIZE: {{ .Values.bpa.config.creddef.revocationRegistrySize | quote }}
  BPA_TITLE: {{ .Values.bpa.config.title | quote }}
  BPA_I18N_LOCALE: {{ .Values.bpa.config.i18n.locale | quote }}
  BPA_I18N_FALLBACK_LOCALE: {{ .Values.bpa.config.i18n.fallbackLocale | quote }}
{{- if .Values.bpa.config.imprint.enabled }}
  BPA_IMPRINT_URL: {{ tpl .Values.bpa.config.imprint.url . | quote }}
{{- end }}   
{{- if .Values.bpa.config.privacyPolicy.enabled }}
  BPA_PRIVACY_POLICY_URL: {{ tpl .Values.bpa.config.privacyPolicy.url . | quote }}
{{- end }}
